version: '2'
services:
  vault:
     container_name: vault
     image:  vault:0.11.5    
     network_mode:  "host"
#    ports:
#      - 8200:8200
     volumes:
       - ./config/vault:/config
       - ./config/vault/policies:/policies
     environment:
         TZ: Asia/Taipei
         VAULT_ADDR: "http://127.0.0.1:8200"
         VAULT_API_ADDR:  "http://127.0.0.1:8200"
     entrypoint:  vault server -config=/config/vault.conf

